# Generated by Django 4.2.2 on 2023-08-05 07:09

import base.utils.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_box_setting_alter_configuration_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.JSONField(encoder=base.utils.encoder.EnhancedJSONEncoder),
        ),
    ]
